package Model;
// Generated Jul 10, 2017 9:55:40 PM by Hibernate Tools 4.3.1



/**
 * Galery generated by hbm2java
 */
public class Galery  implements java.io.Serializable {


     private Integer id;
     private String path;

    public Galery() {
    }

    public Galery(String path) {
       this.path = path;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


