package Model;
// Generated Jul 10, 2017 9:55:40 PM by Hibernate Tools 4.3.1



/**
 * Usergalery generated by hbm2java
 */
public class Usergalery  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int imageId;
     private int carId;

    public Usergalery() {
    }

    public Usergalery(int userId, int imageId, int carId) {
       this.userId = userId;
       this.imageId = imageId;
       this.carId = carId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public int getCarId() {
        return this.carId;
    }
    
    public void setCarId(int carId) {
        this.carId = carId;
    }




}


