package Model;
// Generated Jul 10, 2017 9:55:40 PM by Hibernate Tools 4.3.1



/**
 * Userreviewstats generated by hbm2java
 */
public class Userreviewstats  implements java.io.Serializable {


     private Integer id;
     private Long averageStars;
     private short reviewType;

    public Userreviewstats() {
    }

	
    public Userreviewstats(short reviewType) {
        this.reviewType = reviewType;
    }
    public Userreviewstats(Long averageStars, short reviewType) {
       this.averageStars = averageStars;
       this.reviewType = reviewType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Long getAverageStars() {
        return this.averageStars;
    }
    
    public void setAverageStars(Long averageStars) {
        this.averageStars = averageStars;
    }
    public short getReviewType() {
        return this.reviewType;
    }
    
    public void setReviewType(short reviewType) {
        this.reviewType = reviewType;
    }




}


