package Model;
// Generated Jul 10, 2017 9:55:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usercarrents generated by hbm2java
 */
public class Usercarrents  implements java.io.Serializable {


     private Integer id;
     private Date dateStart;
     private Date dateEnd;
     private int userId;
     private int carId;

    public Usercarrents() {
    }

    public Usercarrents(Date dateStart, Date dateEnd, int userId, int carId) {
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.userId = userId;
       this.carId = carId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getCarId() {
        return this.carId;
    }
    
    public void setCarId(int carId) {
        this.carId = carId;
    }




}


